version: '3'

services:
    parmesan:
        image: parmesan:latest
        container_name: parmesan
        restart: unless-stopped
        logging:
            options:
                max-size: "4096m"
        ports:
          - "5000:5000"
        volumes:
          - type: bind
            source: ./data/parmesan_data/
            target: /parmesan/data/

    rust:
        image: rust:latest
        container_name: rust
        restart: unless-stopped
        logging:
            options:
                max-size: "4096m"
        ports:
            - "8080:8080"

    manual_flags:
        image: manual_flags:latest
        container_name: manual_flags
        restart: unless-stopped
        logging:
            options:
                max-size: "4096m"
        environment:
          - SQLITE_PATH=/tmp/manual_flags/db.sqlite
          - PARMESAN_URL=http://parmesan:5000/spoopy_admin_url_replace_me_pls
        ports:
          - "4000:80"
        volumes:
          - type: bind
            source: ./data/manual_flags_data/
            target: /tmp/manual_flags/
