[package]
name = "prolog"
version = "0.1.0"
edition = "2021"
description = "PARMSFCTFPMM flag submission"
readme = "../README.md"
repository = "https://github.com/ZeusWPI/PARMSFCTFPMM"
publish = false

[profile.release]
opt-level = 3
lto = "thin"
strip = true
codegen-units = 1

[dependencies]
